# Generated by Django 5.0.4 on 2024-05-09 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('MaLoaiSP', models.AutoField(primary_key=True, serialize=False)),
                ('TenLoaiSP', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.AutoField(primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=255)),
                ('ThuongHieu', models.CharField(max_length=255)),
                ('NguonGoc', models.TextField()),
                ('MoTa', models.TextField()),
                ('GiaCu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GiaMoi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Anh', models.URLField()),
                ('Anh1', models.URLField()),
                ('NgayNhap', models.DateField()),
                ('MaLoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.loaisanpham')),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('MaGH', models.AutoField(primary_key=True, serialize=False)),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SoLuong', models.IntegerField()),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sanpham')),
            ],
        ),
    ]
