# Generated by Django 5.0.4 on 2024-05-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='hoangkhoi1223', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
