# Generated by Django 5.0.4 on 2024-05-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_giohang_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giohang',
            name='MaSP',
        ),
        migrations.AlterField(
            model_name='giohang',
            name='SoLuong',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='TongTien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='GioHangItem',
            fields=[
                ('MaGHI', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField(default=0)),
                ('TongTien', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sanpham')),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.giohang')),
            ],
        ),
    ]
