# Generated by Django 5.0.4 on 2024-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_giohang_masp_alter_giohang_soluong_and_more'),
    ]

    operations = [
        
    ]
