# Generated by Django 5.0.4 on 2024-05-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_loaisanpham_maloaisp_loaisanpham_id'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='sanpham',
            name='Anh',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='Anh1',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
